name: ADS-B Radar
version: "0.1.2"
slug: adsb_radar
description: Decode a USB RTL-SDR receiver with dump1090 and view aircraft in Virtual Radar Server.
url: https://github.com/maxneuvians/home-assistant-apps/tree/main/adsb_radar
arch:
  - amd64
startup: application
boot: auto
init: true
usb: true
homeassistant_api: true
ingress: true
ingress_port: 8099
ingress_entry: /
panel_icon: mdi:airplane
panel_title: ADS-B Radar
panel_admin: true
stage: experimental
options:
  device_serial: ""
  gain: -10
  ppm: 0
  vrs_username: admin
  vrs_password: ""
schema:
  device_serial: str
  gain: float(-10,49.6)
  ppm: int(-200,200)
  latitude: float(-90,90)?
  longitude: float(-180,180)?
  vrs_username: str
  vrs_password: password
